// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"fgstgu/go/src/c/gin/easy-user-api/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserAPI(db *gorm.DB) user.UserAPI {
	userRepository := user.ProvideUserRepository(db)
	userService := user.ProvideUserService(userRepository)
	userAPI := user.ProvideUserAPI(userService)
	return userAPI
}
